name: Go
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Download all Go modules
        run: go mod download

      - name: Check that modules are tidy
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Run Tests
        run: go test -v ./...
